### ISSUE TITLE
Rework Bot base

### ISSUE THREAD

**Issue by DxsSucuk** [Ree6-Applications/Ree6#139]

**Comment by Taz03** [comment]
what exactly to do in the rework??

**Comment by DxsSucuk** [comment]
Well basically going throu the base of the bot and checking what could be reworked.

For example the LoggerQueue System would need a full rework since its awful for performance.
Or a rework of the BotWorker/BotVersion since those two need manualy updating which is not really great.
The Config System would need rework to support older config files (automatic migration), and a warning incase the config is too old.

**Comment by DenuxPlays** [comment]
Isnt this done?

**Comment by DxsSucuk** [comment]
Should be
