### ISSUE TITLE
Linux cannot launch

### ISSUE THREAD

**Issue by dnk-codes** [Ree6-Applications/Ree6#19]
I tried running the .jar file but I am getting this error `ava.io.FileNotFoundException: config.yml (No such file or directory)`
I updated my java to version 17 but don't know what to do next

**Comment by DxsSucuk** [comment]
Well it should automaticly create a config.yml file. If it doesn't just created one in the same directory as the JAR.

**Comment by dnk-codes** [comment]
> 

there is a config file created but it still says the error

**Comment by DxsSucuk** [comment]
Is it  a config.yml file? Not a directory. And the config.yml file should be in the same folder as the jar.

**Comment by dnk-codes** [comment]
> Is it a config.yml file? Not a directory. And the config.yml file should be in the same folder as the jar.

it created the config.yml file after some tinkering, i just need to fill it out now probably but idk how

**Comment by DxsSucuk** [comment]
That shouldn't be that difficult.
For the mysql part you just put in your MySQL login information. Giphy you add your own Giphy API-Token that you get by creating a new Giphy Application. For Dagpi you have to apply over at https://dagpi.xyz . For raygun just create a new Raygun application at raygun.com . For the Spotify part create a new Spotify Application and use the creds, same for twitch, twitter and YouTube. At the end you put a release Token which is used for release version (public use), and one developer Token which is used for test versions (private use).

**Comment by dnk-codes** [comment]
> That shouldn't be that difficult. For the mysql part you just put in your MySQL login information. Giphy you add your own Giphy API-Token that you get by creating a new Giphy Application. For Dagpi you have to apply over at https://dagpi.xyz . For raygun just create a new Raygun application at raygun.com . For the Spotify part create a new Spotify Application and use the creds, same for twitch, twitter and YouTube. At the end you put a release Token which is used for release version (public use), and one developer Token which is used for test versions (private use).

thank you i have done almost everything, can i host it then on my cloud server?

**Comment by DxsSucuk** [comment]
You don't need to put an Dev Token if you don't think about testing new Features you add yourself. And yeah you can host it on your own Server and use the code for your own Discord bot, as long as you give us credits.

**Comment by dnk-codes** [comment]
> You don't need to put an Dev Token if you don't think about testing new Features you add yourself. And yeah you can host it on your own Server and use the code for your own Discord bot, as long as you give us credits.

I know that this is closed but yes. I will only be making small adjustments for myself and keep the credits accessible.

**Comment by DxsSucuk** [comment]
Thats alright!
