### ISSUE TITLE
Oracle Cloud GNU

### ISSUE THREAD

**Issue by dnk-codes** [Ree6-Applications/Ree6#20]
CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES or GUILD_MEMBERS.)
I get this message whenever i try to run the jar file

**Comment by dnk-codes** [comment]
It starts Shutdown init right after

**Comment by DxsSucuk** [comment]
Go to your Discord Development Tab, and go to your Application, then to your Bot, then set every Intent to on.
