### ISSUE TITLE
[Bug]: SQLite Missing Driver

### ISSUE THREAD

**Issue by Justman10000** [Ree6-Applications/Ree6#248]
### Contact Details

Discord: Justman10000#0702

### What happened?

> org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
> Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:sqlite:storage/Ree6.db

### Version

v2 (Current)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DxsSucuk** [comment]
Issue got fixed in https://github.com/Ree6-Applications/Ree6-SQL/commit/8e7b5b6af79ddb0d9921a1451e90feef993c20c2
