### ISSUE TITLE
[Bug]: Unable to display Chinese

### ISSUE THREAD

**Issue by YashajinAlice** [Ree6-Applications/Ree6#400]
### Contact Details

.alice9527 （Discord）

### What happened?

"As the title says, 
Chinese fonts cannot be displayed properly in the welcome-triggered image. It includes the word '等級' (level)

### Version

v1 (LTS)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DxsSucuk** [comment]
Should now be fixed by allowing users when selfhosting to set the Font of the Text.
And if the Font can't display it just fallback to Arial.
