### ISSUE TITLE
[FEATURE] adding a way to send a recording via discord.

### ISSUE THREAD

**Issue by Hexa0110** [Ree6-Applications/Ree6#401]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the issue is. Ex. I'm always frustrated when [...]
Yes, for example. A human made a discord bot from a pterodactyl panel and doesnt have a server to host the web interface. He cant play the recordings via discord

**Describe the solution you'd like**
Adding a way to send a audio recording via discord or an mp3 file

**Describe alternatives you've considered**
I dont have one

**Additional context**
Nah

**Comment by DxsSucuk** [comment]
Closing this since I finally added it!
Just gotta wait for the translations to release it in hopefully 3.0.13
