### ISSUE TITLE
[Bug]: `/disconnect` not working if no music is playing

### ISSUE THREAD

**Issue by jiriks74** [Ree6-Applications/Ree6#524]
### What happened?

When there are no more songs in the queue the bot stays connected and the `/disconnect` command is not working. It works when the bot is playing music but not otherwise:
![image](https://github.com/Ree6-Applications/Ree6/assets/54378412/14907fec-4409-4887-aae7-d54360030ea8)
![image](https://github.com/Ree6-Applications/Ree6/assets/54378412/867d94a6-7571-45ff-8648-617c55c63db2)

### Version

v3 (Current)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DxsSucuk** [comment]
Has been fixed with the latest commit on master.
