### ISSUE TITLE
[Bug]: pterodactyl egg doesn't set up recording link properly

### ISSUE THREAD

**Issue by jiriks74** [Ree6-Applications/Ree6#581]
### Contact Details

@jiriks74

### What happened?

Ree6 egg sets up recording url to `https://cp.ree6.de/external/recording` instead of the one set in setup. 

Here is the relevant part of `config.yml`:

```
        record: https://<my-url>
        recording: https://cp.ree6.de/external/recording
```

The `<my-url>` is set using the Pterodactyl Startup settings:
![image](https://github.com/Ree6-Applications/Ree6/assets/54378412/ef9580d6-31b8-4d77-80e0-1db76e306644)

 As you see it works for `record:` but not for `recording:`. I have to modify the url manually for it to be the correct value.

### Version

v3 (Current)

### Relevant log output

```shell
No relevant logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jiriks74** [comment]
Manually modifying the `config.yml` works as a temporary fix

**Comment by jiriks74** [comment]
also could there be a new release made for both the bot and the web-backend? Currently they're out of sync on the database structure and don't run alongside each other. Currently I have to hunt the CI/CD pipeline for artifacts and update everything manually.

**Comment by DxsSucuk** [comment]
I will be releasing a new Version for the Bot soon.
Currently trying to figure out some changes TikTok made within their API so I can readd support for the TikTok Notifier.
After I finish doing that a new Bot release will be published. For the Webinterface I will be waiting for the PR you made, if it works fine I will check it on my end. After that I will merge it and release a new version.

**Comment by DxsSucuk** [comment]
This specific bug should be fixed in this PR https://github.com/pelican-eggs/eggs/pull/2913.
Keeping this open until its being merged.

**Comment by DxsSucuk** [comment]
I will release a new Webinterface version to fix compatibility Issues and finally have docker support. There sadly will not be a new Bot release, since I need to update the egg and find a solution for the TikTok Notifier, since they change some stuff that prevents me from getting website content.

**Comment by jiriks74** [comment]
Is TikTok worth fixing RN? It's getting banned in the US so depending on where you are you may not be able to run it after some time.

**Comment by DxsSucuk** [comment]
I live in Germany, so the ban does not affect me. And neither do I use TikTok.
Also for this Issue itself there is a new PR https://github.com/pelican-eggs/chatbots/pull/2 gotta wait for it to merge.

**Comment by DxsSucuk** [comment]
I will close this ticket, since the bug itself has been fixed by the merged PR https://github.com/pelican-eggs/chatbots/pull/2
