### ISSUE TITLE
Account Apps

### ISSUE THREAD

**Issue by ErrorHunter1** [Ree6-Applications/Ree6#592]
# English
Discord added the ability to add Apps (User installed Bots) to a account. It would be nice if commands such as /hug, /kiss and /slab worked every.

# Original
Es ist nun möglich Apps (Bots) zu seinem Account hinzuzufügen. Dies wäre so geil wenn /hug /kiss /slab überall gehen

**Comment by ErrorHunter1** [comment]
![image](https://github.com/Ree6-Applications/Ree6/assets/106146185/545ba966-d2b7-4525-9646-026deab97935)

**Comment by DxsSucuk** [comment]
Feature will be worked on once [this PR](https://github.com/discord-jda/JDA/pull/2633) is merged into master and deemed stable by the JDA maintaners.

**Comment by jalpp** [comment]
I can work on this once JDA merges it

**Comment by DxsSucuk** [comment]
Should be implemented in the v4 branch.
https://github.com/Ree6-Applications/Ree6/tree/dev/v4-userapp

**Comment by DxsSucuk** [comment]
Userapps got implemented into V4, feel free to test it out.
